apiVersion: ds.cpd.ibm.com/v1alpha1
kind: DataStage
metadata:
  name: {{ .Values.name }}     
  namespace: {{ .Values.cpd_namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.syncWave | default "-3" | quote }}  
spec:
  license:
    accept: true
    license: Enterprise   
  version: {{ .Values.spec.version }}
  storageClass: {{ .Values.spec.storageClass }}
  

